### ISSUE TITLE
Installer failing

### ISSUE THREAD

**Issue by DJPlaya** [TakerMc/flood_ynh#3]
Hello,
trying to install this app in Yunohost raises an error and aborts the action.
My host system in an Raspberry Pi 4 running YNH 4.3.6.3.
Install Log > https://paste.yunohost.org/raw/ijixizowij

**Comment by Taikeur** [comment]
Hello @DJPlaya ,

This repository is no longer maintained.
Please submit your issue to this repository: https://github.com/YunoHost-Apps/flood_ynh
